# **Numpy**

# **What is Numpy?**
NumPy is a general-purpose array-processing package package in Python used for Scientific Computing. It provides a high-performance multidimensional array object, and tools for working with these arrays. This can be an alternative to MATLAB. Numpy is a portmanteau of the words NUMerical and Python. 

# **Why use Numpy?**
*   NumPy uses much less memory to store data
*   It is Fast
*   Mathematical operations on NumPy are easy to perform
*   It works very well with SciPy and other Libraries
*   It has lots of built-in functions
*   It has universal functions

# **Features of Numpy-**
*  NumPy stands on CPython, a non optimizing bytecode interpreter.
*  Multidimensional arrays.
*  Functions & operators for these arrays
*  Python alternatives to MATLAB.
*  ndarray- n-dimensional arrays.
*  Fourier transforms & shapes manipulation.
*  Linear algebra & random number generation.

# **How it is used-**
You can import NumPy it as-
>>> import numpy as np


In [1]:
!pip install numpy       #To load numpy

In [2]:
import numpy as np      #import numpy

# **The Basics**

In [3]:
x = np.array([4,5,6,7,8])        #initialize an array
x

array([4, 5, 6, 7, 8])

In [4]:
type(x)          #to check type

numpy.ndarray

In [5]:
x = np.array([[1,2,3],[4,5,6]], dtype='int32')           #initializing 2d array iwth type int32
print(x)

[[1 2 3]
 [4 5 6]]


In [6]:
x = np.array([(1,2,3),(4,5,6.1)])           #upcasting
x

array([[1. , 2. , 3. ],
       [4. , 5. , 6.1]])

In [7]:
x.ndim              # To get Dimension

2

In [8]:
x.shape               # To Get Shape

(2, 3)

In [9]:
x.dtype            # To Get Type

dtype('float64')

In [10]:
x.size       # To Get number of elements

6

In [11]:
x.size *x.itemsize            #to get total size

48

# **1) How to create a boolean array?**

Hint: Create a 3×3 numpy array of all True’s

In [12]:
np.ones([3,3],dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**2) Create an array and print its attribute**

In [13]:
arr=np.ones([3,3])
print("Array Shape is: ", arr.shape)
print("Array dimensions are ", arr.ndim)
print("Length of each element of array in bytes is ", arr.size)

Array Shape is:  (3, 3)
Array dimensions are  2
Length of each element of array in bytes is  9


# **Different Types of Arrays**

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
type(np.ones(5)[0])

numpy.float64

In [16]:
np.ones((5,6), dtype='int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [17]:
np.zeros((2,3))             

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.empty(4)

array([5.e-324, 5.e-324, 5.e-324, 0.e+000])

In [19]:
np.arange(0,10)          #similar to range function in python(only difference is it can take floats also)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,11.5,2) 

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [21]:
np.arange(0,10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
np.linspace(0,10,5)               #from 0 to 10 with 5 elements

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0,10,endpoint=True,retstep=False)         

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
np.logspace(0,10,base=2)

array([1.00000000e+00, 1.15195282e+00, 1.32699530e+00, 1.52863599e+00,
       1.76091654e+00, 2.02849277e+00, 2.33672798e+00, 2.69180039e+00,
       3.10082705e+00, 3.57200647e+00, 4.11478293e+00, 4.74003581e+00,
       5.46029763e+00, 6.29000526e+00, 7.24578931e+00, 8.34680745e+00,
       9.61512839e+00, 1.10761743e+01, 1.27592302e+01, 1.46980313e+01,
       1.69314386e+01, 1.95042185e+01, 2.24679395e+01, 2.58820063e+01,
       2.98148502e+01, 3.43453008e+01, 3.95641662e+01, 4.55760529e+01,
       5.25014628e+01, 6.04792082e+01, 6.96691946e+01, 8.02556253e+01,
       9.24506940e+01, 1.06498838e+02, 1.22681637e+02, 1.41323458e+02,
       1.62797956e+02, 1.87535565e+02, 2.16032123e+02, 2.48858814e+02,
       2.86673613e+02, 3.30234477e+02, 3.80414538e+02, 4.38219601e+02,
       5.04808306e+02, 5.81515352e+02, 6.69878251e+02, 7.71668141e+02,
       8.88925293e+02, 1.02400000e+03])

In [25]:
np.random.rand(3,3)            ## random array

array([[0.78376797, 0.59452591, 0.21547545],
       [0.16248656, 0.34771234, 0.78177643],
       [0.31285097, 0.96951857, 0.36267621]])

In [26]:
np.random.randn(4,4)

array([[ 0.37267163,  0.48051141, -1.3883996 , -0.48760535],
       [ 0.65521597,  0.31913093,  1.57268867, -1.18669129],
       [-0.10816562,  0.5319951 ,  1.12849335,  1.15641318],
       [ 0.0575516 , -2.10034795, -0.871984  ,  0.24276629]])

In [27]:
np.random.randint(0,100,8)

array([ 9, 80, 45,  5, 49, 89, 28, 73])

In [28]:
np.random.random_sample((1,5))

array([[0.04138869, 0.50448777, 0.66946355, 0.99844537, 0.26705913]])

In [29]:
np.identity(5)        #Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 3) Create a 4X2 integer array and Prints its attributes

In [30]:
arr = np.empty([4,2], dtype = 'int32') 
print(arr)

print("Array Shape is: ", arr.shape)
print("Array dimensions are ", arr.ndim)
print("Length of each element of array in bytes is ", arr.size)

[[         0 1074003968]
 [         0 1075052544]
 [         0 1075707904]
 [         0 1076101120]]
Array Shape is:  (4, 2)
Array dimensions are  2
Length of each element of array in bytes is  8


**4)How to extract items that satisfy a given condition from 1D array?**

In [31]:
#Extract all odd numbers from arr
x=np.arange(10)
x[x%2==1]             

array([1, 3, 5, 7, 9])

# **Accessing/Changing specific elements, rows, columns, etc**

In [32]:
a = np.array([[1,2,3,6,8,7.8],[8,9,10,11,3,7]])
print(a)                                                            #upcasting

[[ 1.   2.   3.   6.   8.   7.8]
 [ 8.   9.  10.  11.   3.   7. ]]


In [33]:
a[0][1]

2.0

In [34]:
a[1, 5]           # To Get a specific element [r, c]

7.0

In [35]:
# Get a specific row 
a[0, :]

array([1. , 2. , 3. , 6. , 8. , 7.8])

In [36]:
a

array([[ 1. ,  2. ,  3. ,  6. ,  8. ,  7.8],
       [ 8. ,  9. , 10. , 11. ,  3. ,  7. ]])

In [37]:
a[0,1:4]

array([2., 3., 6.])

In [38]:
a[0, 1:-1:2]             #startindex:endindex:stepsize

array([2., 6.])

**5) How to swap two rows in a an array?**

In [39]:
x=np.arange(6).reshape(2,-1)
print(x)
print("After Swaping")
print(x[[1,0],:])

[[0 1 2]
 [3 4 5]]
After Swaping
[[3 4 5]
 [0 1 2]]


**6)  Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10**

In [40]:
arr = np.arange(100, 200, 10).reshape(5,2)
arr

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

**7) How to reverse the columns of a an array?**

In [41]:
x=np.arange(6).reshape(2,-1)
x[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3]])

[33]:
# **# Some useful conditions for Exploratory Data Analysis**

In [42]:
arr=np.array([  1,   2,   3, 100, 100])
val=2

arr[arr<3]

array([1, 2])

In [43]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# **Maths**

In [44]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [45]:
a+2             #similarly you can perform division, Multiplication, subtraction, power of,sqrt, log on element-wise 

array([3, 4, 5, 6])

In [46]:

a ** 2

array([ 1,  4,  9, 16])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# **Statistics and linear algebra **

In [48]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(stats)

1

In [50]:
np.max(stats, axis=1)

array([3, 6])

In [51]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [52]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**8)  How to extract numbers between a given range from a numpy array?**

In [54]:
x=np.arange(10,25)
x[(x>15) & (x<22)]


array([16, 17, 18, 19, 20, 21])

## **9) How to stack two arrays vertically?**

In [55]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])