In [ ]:
import numpy as np                     

1) print the version number and configuration.

In [ ]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2) How to swap two columns in a numpy array?

In [ ]:
x=np.arange(6).reshape(2,-1)           ## Setting to -1 automatically decides the number of cols
print(x)
x[:,[1,0,2]]

[[0 1 2]
 [3 4 5]]


array([[1, 0, 2],
       [4, 3, 5]])

3) How to swap two rows in a an array?

In [ ]:
x=np.arange(6).reshape(2,-1)
x[[1,0],:]

array([[3, 4, 5],
       [0, 1, 2]])

4) How to reverse the columns of a an array?

In [ ]:
x=np.arange(6).reshape(2,-1)
x[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3]])

*5*) How to create a boolean array?

Hint: Create a 3×3 numpy array of all True’s

In [ ]:
np.ones([3,3],dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

6) How to extract items that satisfy a given condition from 1D array?



In [ ]:
#Extract all odd numbers from arr
x=np.arange(10)
x[x%2==1]             

array([1, 3, 5, 7, 9])

7) How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
#Replace all odd numbers in arr with -1
x=np.arange(10)
x[x%2==1]=-1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

8) How to reshape an array?

Hint: Convert a 1D array to a 2D array with 2 rows

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

9) How to replace items that satisfy a condition without affecting the original array?

Hint: Replace all odd numbers in arr with -1 without changing arr

In [ ]:
x=np.arange(10)
y=np.where(x%2==1,-1,x)
y

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

10) Create a 4X2 integer array and Prints its attributes

In [ ]:
arr = np.empty([4,2], dtype = 'int32') 
print(arr)

print("Array Shape is: ", arr.shape)
print("Array dimensions are ", arr.ndim)
print("Length of each element of array in bytes is ", arr.size)

[[1 0]
 [1 0]
 [1 0]
 [0 0]]
Array Shape is:  (4, 2)
Array dimensions are  2
Length of each element of array in bytes is  8


11) How to extract all numbers between a given range from a numpy array?
Hint: Get all items between 15 and 22 from array

In [ ]:
x=np.arange(10,25)
x[(x>15) & (x<22)]

array([16, 17, 18, 19, 20, 21])

12) Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [ ]:
arr = np.arange(100, 200, 10).reshape(5,2)
arr

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

13. How to get the positions where elements of two arrays match?

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

14) Return array of odd rows and even columns from given array:
([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [ ]:
arr=np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
arr[::2, 1::2]


array([[ 6, 12],
       [30, 36],
       [54, 60]])

15) How to stack two arrays vertically?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

16) How to stack two arrays horizontally?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

17) Create a null vector of size 10 but the fifth value which is 1

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


18)  Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr=np.random.rand(10,10)
print(np.max(arr))
print(np.min(arr))

0.9962655528350758
0.03388985992279048


19) Create a random vector of size 15 and find the mean value

In [ ]:
vec=np.random.random(15)
np.mean(vec)

0.519458681088485

20)Create a 2d array with 1 on the border and 0 inside 

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


21) Is np.nan == np.nan

In [ ]:
False

False

22) How to print only 3 decimal places in python numpy array?

In [ ]:
arr = np.random.randn(6,2)
print(arr)
np.set_printoptions(precision=3)
print(arr)

[[-1.10371906 -0.53478346]
 [ 0.67991014  0.12238402]
 [-1.28906043 -0.24081191]
 [-0.33850258 -0.41074489]
 [ 0.22599445 -1.11141182]
 [-0.9772879  -0.58117714]]
[[-1.104 -0.535]
 [ 0.68   0.122]
 [-1.289 -0.241]
 [-0.339 -0.411]
 [ 0.226 -1.111]
 [-0.977 -0.581]]


23) How to limit the number of items printed in output of numpy array?

In [ ]:
np.set_printoptions(threshold=8)              # set threshold=np.nan to print full numpy array
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

24) How to compute the mean, median, standard deviation of a numpy array?

In [ ]:
a=np.arange(3,25,2)
mu, med, sd = np.mean(a), np.median(a), np.std(a)
print(mu)
print(med)
print(sd)

13.0
13.0
6.324555320336759


25) How to normalize an array so the values range exactly between 0 and 1?

In [ ]:
a=np.arange(3,30,2).reshape(7,-1)
Smax, Smin = a.max(), a.min()
S = (a - Smin)/(Smax - Smin)
S

array([[0.   , 0.077],
       [0.154, 0.231],
       [0.308, 0.385],
       ...,
       [0.615, 0.692],
       [0.769, 0.846],
       [0.923, 1.   ]])

26) How to find the maximum value in each row of a numpy array 2d?

In [ ]:
np.random.seed(100)
a = np.random.randint(1,20, [5,3])
a

np.amax(a, axis=1)


array([ 9, 17,  3, 18, 17])

27) How to compute the moving average of a numpy array?

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
moving_average(Z, n=3).round(2)

array:  [8 8 3 ... 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

28) Add two NumPy arrays and Modify a result array by calculating the square of each element

In [ ]:
One = np.array([[3,4,5], [21 ,14, 23]])
Two = np.array([[15 ,16, 17], [4 ,7, 1]])
result  = One + Two
print("Result after adding both array" )
print(result)

for num in np.nditer(result, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements")
print(result)

Result after adding both array
[[18 20 22]
 [25 21 24]]

Result array after calculating the square root of all elements
[[324 400 484]
 [625 441 576]]


29)  Split the array into four equal-sized sub-arrays

In [ ]:
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4) 
print(subArrays)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 ...
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


30) what output will be produced?
np.arange(2,8,1)
a) 2,3,4,5,6,7,8

b) 2,3,4,5,6,7,8,9

c) 2,3,4,5,6,7

d) 2,4,6,8

In [ ]:
c)

31) np.array{[4,7]}
a) [ 4 7 ]

b) [ 4 5 6 7 ]

c) [ 4 5 6 ]

d) Error

d) 

32) How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,20,60)
print(np.bincount(Z).argmax())

2


33) Compute a matrix rank

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


34) Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


35) How to get the diagonal of a dot product? 

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

array([1.269, 1.013, 1.273, 1.26 , 1.064])

36) How to sort an array by the nth column?

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 8 8]
 [7 9 0]
 [6 0 7]]
[[6 0 7]
 [8 8 8]
 [7 9 0]]


37) You are given a 1-D array. Print the floor and ceil  of all the elements of Array

In [ ]:
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(np.floor(arr)) 
print(np.ceil(arr)) 

[1. 2. 3. ... 7. 8. 9.]
[ 2.  3.  4. ...  8.  9. 10.]


38) computes the determinant of an array.

In [ ]:
print(np.linalg.det([[1 , 2], [2, 1]]))

-2.9999999999999996


39) There is N*M Matrix. Print the transpose and flatten results.

In [ ]:
my_arr = np.array([[1,2,3],[4,5,6]])
print("The transpose of matrix is")
print (my_arr.transpose())
print("The flatten of matrix is")
print (my_arr.flatten())

The transpose of matrix is
[[1 4]
 [2 5]
 [3 6]]
The flatten of matrix is
[1 2 3 4 5 6]


40)Subtract the mean of each row of a matrix

In [ ]:
X = np.random.rand(5, 10)
print(X - X.mean(axis=1).reshape(-1, 1))


[[-0.119  0.341  0.2   ...  0.283 -0.057 -0.118]
 [-0.206 -0.262  0.017 ...  0.159 -0.037 -0.04 ]
 [ 0.588 -0.168  0.033 ... -0.058 -0.305 -0.318]
 [-0.362 -0.304  0.154 ...  0.238  0.385  0.085]
 [ 0.025 -0.074 -0.12  ...  0.198 -0.244  0.05 ]]


41)  Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.413 0.191 0.706 ... 0.386 0.591 0.138]


42) Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [ ]:
a = np.array([[30,40],[10,20]])
print("Original array:")
print(a)
print("Sort the array along the first axis:")
print(np.sort(a, axis=0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))

Original array:
[[30 40]
 [10 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[30 40]
 [10 20]]
Sort the flattened array:
[10 20 30 40]


43) Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

In [ ]:
complex_num = [4 + 2j, 3 - 2j, 3.4 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)
print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num))

44)Write a NumPy program to shuffle numbers between 0 and 10 (inclusive). 

In [ ]:
x = np.arange(25)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

45) Make an array immutable (read-only) 

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1          #can check by assigning new value

46) How to sum a small array faster than np.sum? 

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

47) Extract the integer part of a random array of positive numbers
Z = np.random.uniform(0,10,10)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z // 1)

48) Write a NumPy program to find the nearest value from a given value in an array.

In [ ]:
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

49) Which of the following function stacks 1D arrays as columns into a 2D array?
a) row_stack
b) column_stack
c) com_stack
d) all of the mentioned

b) column_stack

50) Which of the following function can be used to combine different vectors so as to obtain the result for each n-uplet?
a) iid_
b) ix_
c) ixd_
d) all of the mentioned

b) ix_

51) Write a NumPy program to get the n largest values of an array.

In [ ]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print("n largest values of an array:")
print (x[np.argsort(x)[-n:]])